### ISSUE TITLE
BUG反馈 自动断开连接，然后玩家看不到消息

### ISSUE THREAD

**Issue by SakuranaRanbom** [Vanilla-Non-Benefit-Community/VanillaGlobalChannel#8]
过一段时间不操作后聊天连接断开，自动重连后游戏中发消息看不到。
手动/vgc leave再vgc channel 后才能恢复

环境Ubuntu18, Java17

VanillaGlobalChannel-1.0.2.jar
VGC-Bukkit-1.1.2.jar

vgc后台
```
error occurred while connection opened
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
        at org.apache.tomcat.util.net.NioChannel.read(NioChannel.java:160)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1337)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1226)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:75)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)
 
[ Logout ] §6狼与香辛料亭 has closed the connection
 
 
[ Logout ] §6狼与香辛料亭 has closed the connection
 
error occurred while connection opened
java.io.IOException: Connection timed out
        at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:330)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:296)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:259)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:417)
        at org.apache.tomcat.util.net.NioChannel.read(NioChannel.java:160)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1337)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1226)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:75)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)
 
[ Logout ] §d资源服 has closed the connection
```
MC服务器显示信息：
```
[07:38:29 INFO]: [BukkitVGC] [ Vanilla-Network ] 中央聊天服务器连接失败，正在重试...
[07:38:29 INFO]: [BukkitVGC] [ Vanilla-Network ] 中央聊天服务器连接成功。
[07:38:29 INFO]: [BukkitVGC] [ Vanilla-Network ]  正在初始化频道系统...
[07:38:29 INFO]: [BukkitVGC] [ Vanilla-Network ]  正在获取所有服务器信息...
[07:38:29 INFO]: [BukkitVGC] [ Vanilla-Network ]  正在创建频道用户列表容器 [ 1/3 ]
[07:38:29 INFO]: [BukkitVGC] [ Vanilla-Network ]  正在创建频道消息队列 [ 2/3 ]
[07:38:29 INFO]: [BukkitVGC] [ Vanilla-Network ]  正在注册频道监听器 [ 3/3 ]
[07:38:29 INFO]: [BukkitVGC] [ Vanilla-Network ]  频道系统初始化完成！
[07:38:29 INFO]: [BukkitVGC] [ Vanilla-Network ]  服务器信息加载完毕！
```

**Comment by SakuranaRanbom** [comment]
现在是断开连接后，没有显示重新连上，但VGC可以收到mc服务器发的信息。同时mc服务器无法看到玩家聊天发的消息。
```
[ Logout ] §6狼与香辛料亭 has closed the connection


[ Logout ] §6狼与香辛料亭 has closed the connection

1|1|Leo_Ranbom|11|1|Leo_Ranbom|31|1|Leo_Ranbom|`1|1|Leo_Ranbom|31|1|Leo_Ranbom|21|1|Leo_Ranbom|31|1|Leo_Ranbom|11|1|Leo_Ranbom|21|1|Leo_Ranbom|31|1|Leo_Ranbom|11|1|Leo_Ranbom|21|1|Leo_Ranbom|31|1|Leo_Ranbom|11|1|Leo_Ranbom|测试
```
![image](https://user-images.githubusercontent.com/48652800/206197807-48043105-7ceb-4f58-bb43-ec9ec5c24b67.png)

**Comment by MikkoAyaka** [comment]
近期正在准备重构了
